all:
	@for i in ex0*/; do \
		(cd $$i && $(MAKE)); \
	done

clean:
	@for i in ex0*/; do \
		(cd $$i && $(MAKE) clean); \
	done

fclean:
	@for i in ex0*/; do \
		(cd $$i && $(MAKE) fclean); \
	done

re:
	@for i in ex0*/; do \
		(cd $$i && $(MAKE) re); \
	done